//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QQCourse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public Tests()
        {
            this.Questions = new HashSet<Questions>();
            this.Results = new HashSet<Results>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.TimeSpan Time { get; set; }
        public Nullable<int> MinScore { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> CreatorId { get; set; }
    
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<Results> Results { get; set; }
        public virtual Users Users { get; set; }
    }
}
