//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QQCourse.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Notifications = new HashSet<Notifications>();
            this.Requests = new HashSet<Requests>();
            this.Results = new HashSet<Results>();
            this.Tests = new HashSet<Tests>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public string Name { get; set; }
        public string Middlename { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Gender { get; set; }
        public byte[] Avatar { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string NeedTraining { get; set; }
    
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual ICollection<Results> Results { get; set; }
        public virtual ICollection<Tests> Tests { get; set; }
    }
}
